"""Generate one-shot equation candidates from literature retrieval only.

This script is intentionally separate from the main pipeline and from
active_learning_uncertainty.py. It tests a narrower question:

    Can the retrieved literature alone suggest useful equation structures
    before the model sees FLIPMM fitting/validation feedback?

The script reuses existing project pieces:

* src.config_loader.load_config / require_env
* src.knowledge.build_retriever for local literature retrieval
* the configured input/output symbols from config.yaml

It writes a Python file containing generated equation functions. Later, those
functions can be plugged into the active-learning sandbox for comparison against
the equations selected by the original data-fitting pipeline.

Run:
    uv run python generate_one_shot_literature_equations.py --count 12
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import openai

from src.config_loader import load_config, require_env, resolve_path, variable_phrase
from src.knowledge import build_retriever


DEFAULT_OUTPUT = "output/one_shot_literature_equations.py"


def _prompt(cfg: dict, literature_context: str, count: int) -> str:
    """Build the one-shot literature-only equation-generation prompt."""
    inputs = cfg["variables"]["inputs"]
    output = cfg["variables"]["output"]
    input_symbols = cfg["input_symbols"]
    output_symbol = cfg["output_symbol"]
    unpack = ", ".join(input_symbols)

    return f"""
Use only the retrieved literature context below to propose candidate analytical
equation structures for {output['name']} ({output_symbol}).

Retrieved literature context:
{literature_context}

Task:
Generate {count} diverse Python equation functions for:

    {output_symbol} = f({", ".join(input_symbols)})

These are one-shot literature-derived hypotheses. Do not use any FLIPMM dataset
values, validation scores, fitted results, or prior generated equations. The
functions should be plausible structures suggested by the text: linear,
interaction, power-law, logarithmic, saturation, threshold, exponential, or
polynomial terms are all acceptable if the literature context supports them.

Inputs:
{variable_phrase(inputs)}

Output:
{output['name']} ({output_symbol})

Strict formatting rules:
1. Return only Python code.
2. Include exactly {count} function definitions.
3. Name them literature_model_1, literature_model_2, ..., literature_model_{count}.
4. Each function must have the form:

   def literature_model_i(X, a0, a1, ...):
       {unpack} = X
       {output_symbol} = ...
       return {output_symbol}

5. Use only Python, numpy as np, and math-safe operations.
6. For log terms, use np.log(np.maximum(variable, 1e-12)).
7. Keep each equation reasonably simple, preferably 4 to 10 fitted parameters.
8. Do not include comments, markdown fences, prose, imports, or explanations.
""".strip()


def _clean_generated_code(text: str) -> str:
    """Remove common markdown wrappers while preserving generated functions."""
    text = text.strip()
    text = text.replace("```python", "").replace("```", "").strip()
    match = re.search(r"def\s+literature_model_1\s*\(", text)
    return text[match.start() :].strip() if match else text


def _function_names(code: str) -> list[str]:
    return re.findall(r"def\s+(\w+)\s*\(", code)


def _validate_generated_code(code: str, expected_count: int) -> list[str]:
    """Compile generated code and ensure the expected functions exist."""
    names = _function_names(code)
    expected = [f"literature_model_{i}" for i in range(1, expected_count + 1)]
    missing = [name for name in expected if name not in names]
    if missing:
        raise RuntimeError(
            "Generated code did not include the expected functions: "
            + ", ".join(missing)
        )

    namespace = {"np": __import__("numpy"), "numpy": __import__("numpy")}
    exec(code, namespace)  # noqa: S102 - local generated code we immediately validate.
    for name in expected:
        if not callable(namespace.get(name)):
            raise RuntimeError(f"{name} was not callable after generation.")
    return expected


def _write_equation_file(path: Path, code: str, function_names: list[str]) -> None:
    """Write generated equations as an importable Python module."""
    path.parent.mkdir(parents=True, exist_ok=True)
    header = '''"""One-shot equation candidates generated from literature context only.

This file is generated by generate_one_shot_literature_equations.py.
The functions are hypotheses, not validated final models.
"""

import math

import numpy as np


GENERATED_FUNCTIONS = [
'''
    footer = "\n]\n"
    names = "".join(f'    "{name}",\n' for name in function_names)
    path.write_text(header + names + footer + "\n" + code + "\n", encoding="utf-8")


def generate(args: argparse.Namespace) -> Path:
    """Run local retrieval, ask the LLM once, and save equation candidates."""
    cfg = load_config(args.config)
    output_path = resolve_path(cfg, args.output)

    retrieve = build_retriever(cfg)
    literature_context = retrieve()

    client = openai.OpenAI(api_key=require_env("OPENAI_API_KEY"))
    response = client.chat.completions.create(
        model=args.model or cfg["model"]["llm_model"],
        messages=[
            {
                "role": "system",
                "content": (
                    "You generate concise Python equation functions from "
                    "retrieved scientific literature. Return code only."
                ),
            },
            {"role": "user", "content": _prompt(cfg, literature_context, args.count)},
        ],
        temperature=args.temperature,
        max_tokens=args.max_tokens,
    )

    code = _clean_generated_code(response.choices[0].message.content or "")
    function_names = _validate_generated_code(code, args.count)
    _write_equation_file(output_path, code, function_names)
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default=None, help="Optional config YAML path.")
    parser.add_argument("--count", type=int, default=12, help="Number of equation functions.")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Generated Python output path.")
    parser.add_argument("--model", default=None, help="Override LLM model from config.yaml.")
    parser.add_argument("--temperature", type=float, default=0.4)
    parser.add_argument("--max-tokens", type=int, default=2200)
    return parser.parse_args()


if __name__ == "__main__":
    path = generate(parse_args())
    print(f"Wrote one-shot literature equation candidates to: {path}")
