"""Equation generation, fitting and refinement.

Phase 1  -> generate candidate equations from the retrieved knowledge and fit
            them to the training data.
Phase 3  -> iteratively refine the best equations until the validation R2 is
            good enough (or the round budget is exhausted).

The maths is identical to the original notebook; only the variable names,
symbols and limits are now taken from the config so the same code works for any
process.
"""

import inspect
import math
import random
import re

import numpy as np
from scipy.optimize import curve_fit
from sklearn.metrics import mean_squared_error, r2_score

from .config_loader import variable_phrase

# Globals made available to the model code generated by the LLM.
_EXEC_GLOBALS = {"np": np, "numpy": np, "math": math}


# --------------------------------------------------------------------------- #
# Helpers for executing and fitting LLM-generated model code
# --------------------------------------------------------------------------- #
def _clean_code(code: str) -> str:
    """Strip markdown fences the LLM sometimes wraps the code in."""
    return code.replace("```python", "").replace("```", "")


def _extract_function(code: str):
    """Exec generated code and return the first function it defines."""
    match = re.search(r"def\s+(\w+)\s*\(", code)
    if not match:
        raise ValueError("No function definition found in generated code.")
    namespace = dict(_EXEC_GLOBALS)
    exec(code, namespace)
    return namespace[match.group(1)]


def _count_inputs(func) -> int:
    return len(inspect.signature(func).parameters)


def _fit_and_evaluate(func, data: dict):
    """Fit `func` on the training data; return (popt, val_mse, val_r2)."""
    X_train, y_train = data["train"]
    X_val, y_val = data["validation"]

    n_params = _count_inputs(func) - 1  # first arg is X
    popt, _ = curve_fit(func, X_train, y_train, p0=[1] * n_params)

    pred_val = func(X_val, *popt)
    return popt, mean_squared_error(y_val, pred_val), r2_score(y_val, pred_val)


# --------------------------------------------------------------------------- #
# Prompt construction (driven by the config)
# --------------------------------------------------------------------------- #
def _initial_prompt(cfg: dict, context: str) -> str:
    inputs = cfg["variables"]["inputs"]
    out_sym = cfg["output_symbol"]
    out_name = cfg["variables"]["output"]["name"]
    unpack = ", ".join(cfg["input_symbols"])
    return (
        f"Use the following retrieved information:\n{context}\n"
        f"Based on the retrieved relationships between {variable_phrase(inputs)} "
        f"affecting {out_name} ({out_sym}), generate a Python function to model "
        f"{out_sym} as a function of the inputs: ({out_sym}=f({unpack})). "
        "The function can be in various formats, including linear, exponential, "
        "logarithmic, or trigonometric functions. The function should be "
        "formatted as:\n\n"
        "def model(X, a0, ...):\n"
        f"    {unpack} = X\n"
        f"    {out_sym} = ...\n"
        f"    return {out_sym}\n\n"
        "Provide no other context or explanation, just the Python function code. "
        "No extra text. Only utilize the retrieved information to generate the "
        "equation."
    )


def _refine_prompt(cfg: dict, context: str, summary: str) -> str:
    inputs = cfg["variables"]["inputs"]
    out_sym = cfg["output_symbol"]
    out_name = cfg["variables"]["output"]["name"]
    unpack = ", ".join(cfg["input_symbols"])
    syms = ", ".join(cfg["input_symbols"])
    return (
        f"Use the following retrieved information:\n{context}\n\n"
        f"The results for the top models were as follows:\n{summary}\n\n"
        "The R2 scores indicate how well each model fits the data. An R2 score "
        "closer to 1 means a better fit, while a lower R2 score indicates a "
        "weaker fit. Therefore, the models with higher R2 scores and lower MSE "
        "are more reliable and should be given more consideration when creating "
        "new models.\n\n"
        "Based on this information, please generate an improved, complete "
        f"function which leads to a better R2 score for modelling {out_name} "
        f"({out_sym}) as a function of {variable_phrase(inputs)}. "
        "The model should be generated in this format:\n\n"
        "def improved_model(X, a0, ...):\n"
        f"    {unpack} = X\n"
        f"    {out_sym} = ...\n"
        f"    return {out_sym}\n\n"
        "Your task is to alter the equations based on previously retrieved "
        "information and the previous best equations by combining or modifying "
        f"operations (e.g. changing divisions to multiplications, combining "
        f"terms, or introducing new terms) between {syms} and {out_sym}. "
        f"The function must always conclude with return {out_sym}. Please return "
        "the new Python function in the same format as shown above.\n\n"
        "Focus on improving the R2 score accuracy of these models. Do not add "
        "comments. Only return complete Python code, with all equations fully "
        f"defined, and ensure the function ends with \"return {out_sym}\"."
    )


# --------------------------------------------------------------------------- #
# LLM calls
# --------------------------------------------------------------------------- #
def _generate_initial(client, cfg, context):
    mcfg = cfg["model"]
    temperature = random.uniform(mcfg["temperature_min"], mcfg["temperature_max"])
    resp = client.chat.completions.create(
        model=mcfg["llm_model"],
        messages=[
            {"role": "system", "content": "Generates Python code."},
            {"role": "user", "content": _initial_prompt(cfg, context)},
        ],
        max_tokens=mcfg["max_tokens_initial"],
        temperature=temperature,
    )
    return resp.choices[0].message.content


def _generate_refined(client, cfg, context, summary):
    mcfg = cfg["model"]
    out_sym = cfg["output_symbol"]
    resp = client.chat.completions.create(
        model=mcfg["llm_model"],
        messages=[
            {
                "role": "system",
                "content": f"Generates Python code. The function must always "
                f"conclude with return {out_sym}",
            },
            {"role": "user", "content": _refine_prompt(cfg, context, summary)},
        ],
        max_tokens=mcfg["max_tokens_refine"],
    )
    return resp.choices[0].message.content


# --------------------------------------------------------------------------- #
# Result formatting
# --------------------------------------------------------------------------- #
def _summarize(results: list, top_n: int = 20) -> str:
    summary = "\nTop Model Generation Results:\n"
    for r in results[:top_n]:
        summary += f"Model Code:\n{r['model_code']}\n"
        summary += f"Validation MSE:\n{r['validation_mse']}\n"
        summary += f"Validation R2: {r['validation_r2']}\n\n"
    return summary


# --------------------------------------------------------------------------- #
# Phase 1 — initial generation
# --------------------------------------------------------------------------- #
def phase1(client, cfg, retrieve, data, log=print):
    """Generate and fit candidate equations. Returns (summary, sorted_results)."""
    max_iter = cfg["model"]["phase1_iterations"]
    results = []
    iteration = 0

    while iteration < max_iter:
        context = retrieve()
        try:
            model_code = _clean_code(_generate_initial(client, cfg, context))
            log(f"[Phase 1] Iteration {iteration + 1}: generated model code:\n{model_code}")
            func = _extract_function(model_code)
            _, mse_val, r2_val = _fit_and_evaluate(func, data)
            log(f"[Phase 1] validation R2 = {r2_val:.4f}")

            iteration += 1
            results.append(
                {
                    "model_code": model_code,
                    "validation_mse": mse_val,
                    "validation_r2": r2_val,
                }
            )
        except Exception as e:  # noqa: BLE001 - faithful to original behaviour
            log(f"[Phase 1] Iteration {iteration + 1} failed: {e}")
            continue

    results.sort(key=lambda x: x["validation_mse"])
    top = results[:20]
    return _summarize(top), top


# --------------------------------------------------------------------------- #
# Phase 3 — refinement
# --------------------------------------------------------------------------- #
def _refine_once(client, cfg, retrieve, data, summary, results, log=print):
    """One refinement round; appends new candidates to `results`."""
    max_iter = cfg["model"]["phase3_iterations"]
    iteration = 0
    while iteration < max_iter:
        try:
            context = retrieve()
            updated_code = _clean_code(_generate_refined(client, cfg, context, summary))
            log(f"[Phase 3] Iteration {iteration + 1}: generated model code:\n{updated_code}")
            func = _extract_function(updated_code)
            _, mse_val, r2_val = _fit_and_evaluate(func, data)
            log(f"[Phase 3] validation R2 = {r2_val:.4f} | MSE = {mse_val}")

            iteration += 1
            results.append(
                {
                    "model_code": updated_code,
                    "validation_mse": mse_val,
                    "validation_r2": r2_val,
                }
            )
        except Exception as e:  # noqa: BLE001
            log(f"[Phase 3] Iteration {iteration + 1} failed: {e}")
            continue

    results.sort(key=lambda x: x["validation_mse"])
    top = results[:20]
    return _summarize(top), top


def phase3(client, cfg, retrieve, data, summary, results, log=print):
    """Iteratively refine until validation R2 is good enough. Returns (summary, results)."""
    threshold = cfg["model"]["r2_threshold"]
    max_rounds = cfg["model"]["refinement_max_rounds"]

    summary_p3, results_p3 = summary, results
    rounds = 0
    while (1 - results_p3[0]["validation_r2"] > threshold) and rounds < max_rounds:
        log(f"[Phase 3] Refinement round {rounds + 1} "
            f"(best validation R2 = {results_p3[0]['validation_r2']:.4f})")
        summary_p3, results_p3 = _refine_once(
            client, cfg, retrieve, data, summary_p3, results_p3, log=log
        )
        rounds += 1

    if rounds == max_rounds:
        log("[Phase 3] Stopped after the maximum number of refinement rounds.")
    return summary_p3, results_p3


# --------------------------------------------------------------------------- #
# Testing (evaluate the top models on the held-out extrapolative test set)
# --------------------------------------------------------------------------- #
def evaluate_on_test(results, data, top_n: int = 20):
    """Refit the top models on train and evaluate on the test set.

    Returns (best_test_mse, best_test_r2, summary_text).
    """
    summary = "\nTop Model Test Results:\n"
    best_mse = best_r2 = None
    X_test, y_test = data["test"]

    for i in range(min(top_n, len(results))):
        model_code = _clean_code(results[i]["model_code"])
        try:
            func = _extract_function(model_code)
            n_params = _count_inputs(func) - 1
            popt, _ = curve_fit(func, data["train"][0], data["train"][1], p0=[1] * n_params)
            pred_test = func(X_test, *popt)
            mse_test = mean_squared_error(y_test, pred_test)
            r2_test = r2_score(y_test, pred_test)
        except Exception as e:  # noqa: BLE001
            summary += f"Model Code:\n{results[i]['model_code']}\nTest evaluation failed: {e}\n\n"
            continue

        if best_mse is None:
            best_mse, best_r2 = mse_test, r2_test

        summary += f"Model Code:\n{results[i]['model_code']}\n"
        summary += f"Test MSE:\n{mse_test}\n"
        summary += f"Test R2: {r2_test}\n\n"

    return best_mse, best_r2, summary
